name: Update README

permissions:
  contents: write

on:
  push:
    branches:
      - '**'

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Run doc2readme
        uses: docker://codeberg.org/msrd0/cargo-doc2readme:nightly
        with:
          entrypoint: cargo
          args: doc2readme --expand-macros
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Run Python tests
        run: python scripts/docs/gen_supported_devices.py
      - name: Commit updated README/docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md docs/supported-devices.md
          git diff --cached --quiet || git commit -m "docs: update README" && git push
